export const genres = [
  { name: "Tekno Kintueni", contentfulId: "ytpEq87SFMRsuv4r0FuZS" },
  { name: "Jegog", contentfulId: "4Ewfs4sB0N4TGvR86EybfH" },
  { name: "Dangdut", contentfulId: "5CMDzD66jpv6Ap5UnpmoFU" },
  { name: "Nerdcore", contentfulId: "5Ar44CZqvRTaTY6wBmTVKj" },
  { name: "Sound Art", contentfulId: "9ZHdHFErE0JomkHkxFZ0q" },
  { name: "Musique Concrète ", contentfulId: "4Ao2guwu8ilNz3ecCJOQwn" },
  { name: "Lover's Rock", contentfulId: "7kojVe1VFrrQU8l1pWMUtP" },
  { name: "Kenyan Rap", contentfulId: "1SjWcJmBiMOR9rz7GjywqW" },
  { name: "Batida", contentfulId: "59SQi3ICMlqUaF4KjupYwh" },
  { name: "Sound Collage", contentfulId: "1izD7InQBhZo4gboh12Apb" },
  { name: "Post Club", contentfulId: "1ZkPzkR0SJrxoWMT3yXbF8" },
  { name: "Maqam", contentfulId: "RxxJseb2HeiNPvuAEyICc" },
  { name: "Goth", contentfulId: "18cQ7PLndFG4nFsMgqHbXI" },
  { name: "City Pop", contentfulId: "6QNn3rFlygrI6IbYQmCkJY" },
  { name: "Hard Drum", contentfulId: "65HybJkewHPT5pRVy70Pfl" },
  { name: "Coupé-décalé", contentfulId: "4nqQDJpHUy0zpRgmLs086h" },
  { name: "Grunge", contentfulId: "4nnEKIwkSfzEo2oGZwqv9p" },
  { name: "Coldwave", contentfulId: "4SBwp3WRNj42rqFhS7kkLB" },
  { name: "Gabber", contentfulId: "5DybTAZMXVhgZhXsN7uHgN" },
  { name: "Traditional", contentfulId: "2jtL5MlfA2vQzDhTA6iCH9" },
  { name: "Música popular brasileira", contentfulId: "67sZRkgdFfuzAf7pNeXTvG" },
  { name: "Contemporary", contentfulId: "5e3q8ZubuyAuRtp6dihXir" },
  { name: "Yé-yé", contentfulId: "61kBMUCsMBsqZf5Yfl4Z1N" },
  { name: "Twist", contentfulId: "73WvqgE1j5imEfTmhJaNFO" },
  { name: "Andean ", contentfulId: "55NEhKWseY3iF4haH0K5gh" },
  { name: "Technology", contentfulId: "33tvqqbHmIbDLdUBiAd3Gs" },
  { name: "Refugee Support ", contentfulId: "4RG901JhsGzhAttqpSU6Gi" },
  { name: "Miami Bass", contentfulId: "1YcUsuXtfdo8pWTLF6E3AY" },
  { name: "Film", contentfulId: "5VpLrhZme8ADPO8tGnA2dD" },
  { name: "Post-Classical", contentfulId: "3FZ1z3EdUZxEYzh3m1A1f7" },
  { name: "Speed Garage", contentfulId: "R5ArKelYSXTKk4w9nf9MG" },
  { name: "Salsa", contentfulId: "7uwFtfuIlaIVJyeN4ErcH4" },
  { name: "Joropo", contentfulId: "1x9u7fOwzTnNALW1Jp9kBb" },
  { name: "Cumbia", contentfulId: "3km2FUxFTJf809TONbfPFi" },
  { name: "Chants", contentfulId: "6F70g2GO8n5mTfeBiseEKf" },
  { name: "Synthwave", contentfulId: "3R0SyVzRTuvttb84TESo6D" },
  { name: "Lo-fi", contentfulId: "3JW2eIOzeDymdZL3Oz5t49" },
  { name: "Taiwanese Pop", contentfulId: "66lmB04xH7T63rHcmFdPNr" },
  { name: "Street Soul", contentfulId: "5M3MItGKesz9x90klvAdVL" },
  { name: "Ethiopian Pop ", contentfulId: "7wVpm6I7QmzvC1Rj5pxE10" },
  { name: "Polish Jazz", contentfulId: "1b4w2NV2OTpyWZQOtnXHrW" },
  { name: "Roots Reggae", contentfulId: "5LhAUmwC9mB5J7W8Y3XTnh" },
  { name: "Rubadub", contentfulId: "3GiXLmLrbBunfWIW3Fe7fX" },
  { name: "Tropical House", contentfulId: "3kYEifbfckVcKC7vN4kNmK" },
  { name: "Detroit House", contentfulId: "1bbE1mQq1sxdyLw9lQkMss" },
  { name: "Sci-Fi", contentfulId: "2Eo41LcZ8ijknKvnhcoE1V" },
  { name: "Cumbia Rebajada", contentfulId: "IHVeHrADTzVsBZnQqu6kR" },
  { name: "Cumbiaton", contentfulId: "2q44OdQq1Vu7CKUAaLhjfN" },
  { name: "Future Jazz", contentfulId: "1mCgMq4OTYwaAzeT9Or0U7" },
  { name: "Progressive Rock", contentfulId: "1O8fms0Rhy3Utd6psug9KT" },
  { name: "Anatolian Rock", contentfulId: "5REAj9zkIhmibqROhUu5ZM" },
  { name: "Live Set", contentfulId: "1OZyF65DGEmGKrA2V0JZSl" },
  { name: "Minimal House", contentfulId: "470NgROFeUXpUqFoDQwyaf" },
  { name: "Electroclash", contentfulId: "7KVAKpbOA3e9IHpkuRX46p" },
  { name: "Blog House", contentfulId: "3dokpXSWaFC2U3hCGGMk4b" },
  { name: "Fidget House", contentfulId: "64BenPpOcUZDWpF729yeD8" },
  { name: "Mogadishu Disco", contentfulId: "3rZkcH2cHM5OfuObCtN1Go" },
  { name: "Ethio-Jazz", contentfulId: "43uh9K8wfLg4CLLaBhFY7f" },
  { name: "Brazilian Funk", contentfulId: "4CBgvtoDGwBBnXt7dpSKb" },
  { name: "Reggaeton", contentfulId: "1ciA3bGQEcl33rczZtgaOw" },
  { name: "Comedy", contentfulId: "2Jy1IVAFCk56oai6YicRwY" },
  { name: "Psychedelic Folk", contentfulId: "18Sp79xIhYrGTGcQEeDoRH" },
  { name: "Hyperpop", contentfulId: "2f9noIGKKHD8E6WXYJdZq" },
  { name: "Neo Soul ", contentfulId: "6fzYqIObWLeHpXUHuIX1jH" },
  { name: "Tribal", contentfulId: "4zXZtnHXwgvk2LTqOowhM6" },
  { name: "Vogue", contentfulId: "6VPOojAOINs1UxcXFtuCz0" },
  { name: "Deconstructed Club", contentfulId: "2GVQKFkZ2R2Zfq1hVz72Qs" },
  { name: "Leftfield Pop ", contentfulId: "3RUZoVyCDwRF9Axfz88LZo" },
  { name: "Ethiopian Contemporary", contentfulId: "4WGfQJPAXrY6CzQo670Ei5" },
  { name: "Township Jazz", contentfulId: "6Ff3upgpnJvvKiHuGkQW77" },
  { name: "South African Jazz", contentfulId: "2VZWn4nhnzxiCb8oJaBr6m" },
  { name: "Melodic Techno", contentfulId: "6yR1cZZkqX9lWFN8zxXmyL" },
  { name: "Punjabi", contentfulId: "39LEJtqOO8vy6xuUOddKEF" },
  { name: "Latin American", contentfulId: "6SNrPkPcVTvmV2B4tGD5Mo" },
  { name: "Folktronica", contentfulId: "5SX2ikTv2UPUIZLL245ZQk" },
  { name: "Groove", contentfulId: "7covn6HaOyNNbhRCaoBOD1" },
  { name: "Free Improvisation", contentfulId: "HLFDTAD7cyuMsvd6KCDmb" },
  { name: "No Wave", contentfulId: "1qSobEu2AE3ODe6louc7jV" },
  { name: "Future House", contentfulId: "3vkpmapD1z5WdsmDyPdc2s" },
  { name: "Dark Wave", contentfulId: "6qGttmfugRcYOPqPfSDU2i" },
  { name: "Gothic Rock", contentfulId: "7iW7J5aqdeAwADBSRmAdgR" },
  { name: "Jazz Fusion", contentfulId: "2BakvEnCZpbYQHQuYwfP5S" },
  { name: "Motown", contentfulId: "39wwhRiZYhHPCjMjsc1dFs" },
  { name: "Iranian Classical", contentfulId: "2G9pkEjLlu9pSaDVPj2HBG" },
  { name: "Energy", contentfulId: "3saECpuPWjiKaGyzoAeNtF" },
  { name: "Ambient Hardcore", contentfulId: "3poYYh84wlNgpM6CMLMBa8" },
  { name: "Bleep", contentfulId: "1rkWIybGrfz72yxJ1PWW0s" },
  { name: "Hi-NRG", contentfulId: "513Jxn1Uyv0mrp9MpuA1W0" },
  { name: "Industrial Funk", contentfulId: "7aEH8HQlkCp73D4Vca60jy" },
  { name: "140", contentfulId: "5sQBxteyLriH12ckUMfDzY" },
  { name: "Noise", contentfulId: "7D7GQyF5xMm2tGu1krbbwo" },
  { name: "Metal", contentfulId: "P8xjvcCTK2Cj1m5Xph9PK" },
  { name: "Zulu", contentfulId: "610HdaBlrPbruFwTzvsKVJ" },
  { name: "Glitch", contentfulId: "2MYdoNo0IODLqscwyOLr3O" },
  { name: "Desi", contentfulId: "2bNx4RbvxJFjKogTETXwhg" },
  { name: "Sound Therapy", contentfulId: "46R20ZPblxxZUmEGKDFTkL" },
  { name: "Neo Classical", contentfulId: "RUE1eqVH5hbasCyAlVK39" },
  { name: "Rocksteady", contentfulId: "4XOBLJN46gpO2KGzjt1Djf" },
  { name: "Ska", contentfulId: "34owZ1679GUK4dDGP6AhSi" },
  { name: "Onderwereld", contentfulId: "7cpKJcwAF4fpI8tYT3lfJT" },
  { name: "Afro-Techno", contentfulId: "5TgyqH1Q2VwUSW89DprxuG" },
  { name: "Minimal Techno ", contentfulId: "7CzSZHSvA0K8M10WksYNfy" },
  { name: "Intersectional", contentfulId: "jMFAiclIyr8FypMOkxfpv" },
  { name: "Queer", contentfulId: "4dD09X8kRb4QYS3YUQ3e3h" },
  { name: "Gidha", contentfulId: "1vM5qGwNwE15whdbTPylTS" },
  { name: "Composition", contentfulId: "25ny7inOBbXv5kmrXxfJni" },
  { name: "OST", contentfulId: "3toKisvwVCk6zdagH8M7rL" },
  { name: "Italo Disco", contentfulId: "11yLNJuGCF5vrXDg8wmmQG" },
  { name: "Post-Metal", contentfulId: "3qAJ3VsGCCwZec68jTDcDq" },
  { name: "Mental Health", contentfulId: "69U2Lju6eYpa8Jv3ftLeB0" },
  { name: "Baltimore Club", contentfulId: "37fotwNIZwAluLhDBvQFvs" },
  { name: "Avant-folk", contentfulId: "3zvNFzkEe6zOM5VsjYCo8Z" },
  { name: "Dembow", contentfulId: "4Ej0uxjkHZf9E60YH1MBsn" },
  { name: "Doom", contentfulId: "4T5ebvrWLalJo0FdpIvkSa" },
  { name: "Jack House", contentfulId: "6ENEEAfEsSE0PB59dV2vKc" },
  { name: "Poetry ", contentfulId: "38WHzLlHwQcYRV6KZvTMtu" },
  { name: "Space Odyssey", contentfulId: "4gMMtLXssWcbbkfEMZAtdu" },
  { name: "Mento", contentfulId: "35723SAOGwzHn7xhOLqeVJ" },
  { name: "Calypso", contentfulId: "6QApbUnfYHXTXD2KXuCnal" },
  { name: "Raw Distorted Beats", contentfulId: "5ZJw0Ol0y6nl3kidRWdXWp" },
  { name: "Iranian Folk ", contentfulId: "4clRnL4maB7c7H4OJejA1n" },
  { name: "Kiffermusik", contentfulId: "4ZoDxa7Rz7jXnobN9bPPG6" },
  { name: "Eliane Radigue", contentfulId: "2EGctHulkT1vweF0GqyXYU" },
  { name: "Electro-Acoustic", contentfulId: "2X5cc01RYYJOhNNvNYsVvH" },
  { name: "Drone ", contentfulId: "40KViQhL3KI6rFgv9DnOYL" },
  { name: "Prog", contentfulId: "3WBDBkmu3qODiryEsiPPLp" },
  { name: "Deep", contentfulId: "2BN6SmapFTluhtHBeyrXFa" },
  {
    name: "Nogenreneeded Musicforworkflows",
    contentfulId: "4tWfIJQafKwXgB22DDCb2u",
  },
  { name: "Psytrance", contentfulId: "3rBVcQzAXmYD8UYN5wGwC0" },
  { name: "Dance", contentfulId: "4hdTrbiPlqFzu7l9PCzswx" },
  { name: "Leftfield Disco", contentfulId: "4yyhnmWSrjRWSgt8LnYERM" },
  { name: "Dub Reggae", contentfulId: "54tcgTRsbycf8yUITRavtO" },
  { name: "Malombo", contentfulId: "2sFOUGaxjqa1zgfMcaCo5o" },
  { name: "Modern Classical", contentfulId: "74MtSsSRPyjsVxNocxMsFA" },
  { name: "Gqom", contentfulId: "CQqDpBwjm60yWCVHKko26" },
  { name: "Chat Show ", contentfulId: "2QDDVUmwSMKwL2jVUj9AIo" },
  { name: "80's Pop", contentfulId: "2O9BO3Af1ohH4tqF9x72ua" },
  { name: "Community ", contentfulId: "6wIYQz8ViEQk5IREzxclUZ" },
  { name: "Sustainability ", contentfulId: "6Fl38yy20B7xEV9OGyoUKP" },
  { name: "Kwaito", contentfulId: "7mINHskeKna6BNgfe8tup9" },
  { name: "DIY", contentfulId: "2ODcBSrXmeO8EOZb4ab57x" },
  { name: "Soft Rock  ", contentfulId: "5RtirKLWJ6CK5xFv0j7fkI" },
  { name: "World ", contentfulId: "7nDuViUIyIe2iI0coAoe6X" },
  { name: "Mexican Tradicional", contentfulId: "2Fj35p8SCsjHsmJkJ1LTA7" },
  { name: "Dubstep", contentfulId: "44qHkr2X4RS02fjXibwxeV" },
  { name: "Fùjí", contentfulId: "62HsCWm5t2Wrvla93CwVKk" },
  { name: "Soukous", contentfulId: "1aQtDlicb3Wb6uXVug0y4M" },
  { name: "Amapiano", contentfulId: "1zm04C5u6jdcdoEzcrcJ5X" },
  { name: "Alternative", contentfulId: "5NcJYHBnNCRDkR0aRgScA5" },
  { name: "New Beat", contentfulId: "420QSIP7kLu9h6bY3mphdX" },
  { name: "Intelligent Jungle", contentfulId: "jtzy58ox0niVkfnsSaO9N" },
  { name: "Baile Funk", contentfulId: "5jObRhh2QO3m0zYD68oCFi" },
  { name: "UK Garage ", contentfulId: "1l2droL3g2dLXSe8RWFL08" },
  { name: "Free Form", contentfulId: "NDkO2NDJZV7yJkSewYtmA" },
  { name: "Ghetto Tech", contentfulId: "7IWlYXwmudjyjY5zsImGzT" },
  { name: "Ballroom", contentfulId: "18nfDgDOnann639wpoZWTI" },
  { name: "Kuduro", contentfulId: "4nBEyQvbNJkxfLKw1Gen7r" },
  { name: "Roots", contentfulId: "2QvdecU2TTcbZUGhpWdrqM" },
  { name: "Digi-dub", contentfulId: "7jBq49oZbSQmobKL6NdmBV" },
  { name: "Post-Rock", contentfulId: "7JVddCzIZdZX84oUv2tQxg" },
  { name: "Taarab", contentfulId: "2MAcWPx7k5ztqETjQ5xDwW" },
  { name: "Library", contentfulId: "1wRPmwjdvLPDlCdfaLARcg" },
  { name: "Zouk", contentfulId: "6NU5LUJJmKFtaeSFQevUjh" },
  { name: "Post Pop", contentfulId: "2SAYKKqKMTLgXT1oCVD48O" },
  { name: "Rai", contentfulId: "2xxK0BGnisEWttju0OeRyd" },
  { name: "80s", contentfulId: "2rhf97bevcuy4XeGJRFBD5" },
  { name: "Spiritual Jazz", contentfulId: "3NWM8n0mpeAvYp4h2Igybx" },
  { name: "Panafricanism", contentfulId: "5Ob4ftJ45k03Xfm518o5oF" },
  { name: "Interview", contentfulId: "Dk0mcNyLtEK40QjNYMfRC" },
  { name: "Activism", contentfulId: "vZIrGSf131CaNrA66lCe0" },
  { name: "Turkish Psych", contentfulId: "xKJab5RYrwl0QghL5ubpH" },
  { name: "Turkish Disco", contentfulId: "7KmEAqKKITb7pZ1qs461Jx" },
  { name: "Afrofuturism", contentfulId: "5qqo0NpUTGVxag47Dr7y6k" },
  { name: "K-pop", contentfulId: "2P9FCrR1vmALXK2AVUNaQH" },
  { name: "Emo", contentfulId: "38CvtX002dcU5uDfbPNFye" },
  { name: "Healing", contentfulId: "3Y2kzE9k0D0coV6aAMxpxe" },
  { name: "Griot", contentfulId: "5RvJCLpnS8NxNn9ytu8llO" },
  { name: "Slow Jams", contentfulId: "okAAtVLWrJz0VZ3Tk9mgd" },
  { name: "Free Jazz", contentfulId: "1JBNhfJ3SZcTQ0HjPFlWQ1" },
  { name: "Afrofolk", contentfulId: "Jy2wtXnwDdI0XU7TY29oQ" },
  { name: "Afrofusion", contentfulId: "3O1zxKjeLf5Z7huF9QgHut" },
  { name: "Makossa", contentfulId: "2pJuRGtBIxYZ1tXqwXip7i" },
  { name: "Juju", contentfulId: "5jNaTS7SYmSDQgt4NMLQWX" },
  { name: "Highlife", contentfulId: "38Jz5jxpkHoHDpCCQcxba5" },
  { name: "Caribbean", contentfulId: "2cgmzYEMSxc17hw6jgZkXv" },
  { name: "Afrohouse", contentfulId: "1JvyiqVW1O6AHIPKtZt5Nz" },
  { name: "Champeta", contentfulId: "5WqKIGcJzcgAcpiJnnasfe" },
  { name: "Slow Trance", contentfulId: "3WBpQY0QwFk11vdLLBSDIt" },
  { name: "Juke", contentfulId: "5EEBYHXrJU2S2AustBrNIc" },
  { name: "Indie Dance", contentfulId: "26LG87Mj9n0gRwtHmA8WoJ" },
  { name: "Alternative Dance", contentfulId: "42fxkJOW7VXIu27ImeDW0z" },
  { name: "Minimal Synth", contentfulId: "6FgnSwoDKjOy0NDILMktqN" },
  { name: "Instrumental", contentfulId: "1mDus6NivEKFryie4vxd2z" },
  { name: "Illbient", contentfulId: "192oF0MqWjRXNHa8s9Ws4l" },
  { name: "Rock", contentfulId: "7v9qrxKf9t5xG8rRuk2TfY" },
  { name: "Wave", contentfulId: "3jpMv4VFyCUH3yp3NmNbc1" },
  { name: "Electronica", contentfulId: "7J1VmgKlOBe7G1YunwoJ5w" },
  { name: "Dream Pop", contentfulId: "1oztnJFBLxhUY2hbthHtMs" },
  { name: "Avant-Pop", contentfulId: "6cOVtEmOc0SKAzIakMKfxC" },
  { name: "Shoegaze", contentfulId: "3GgGzUtDYtWMaHq0w1WUkf" },
  { name: "Music", contentfulId: "6zBdjGD868bW6HaPMNTPId" },
  { name: "Spiritual", contentfulId: "7lXpinanbCAndTdAX0yjBE" },
  { name: "90s", contentfulId: "6xCCEQhm6tlJheTJogTu47" },
  { name: "Bossa Nova", contentfulId: "2ISWZfhElI0YAkn8QnOMKU" },
  { name: "Nu Jazz", contentfulId: "1JjtgOUPMRwk5jqi1zfFLh" },
  { name: "Art Rock", contentfulId: "9bDZB5ioS0uAfeMnu8qbP" },
  { name: "R&B", contentfulId: "6j5fH0h6eBfqmQriYiBkZb" },
  { name: "Future Beats", contentfulId: "7gDMMvmkuLEVP4OTy6s4aZ" },
  { name: "Funk", contentfulId: "5KZ7cNn4783XV0fw3rVMHy" },
  { name: "Polyrhythms", contentfulId: "3wRLJx47Q7vFjYPQpF98t3" },
  { name: "Percussion", contentfulId: "2XaUrceOca4EOYqgYxFW4b" },
  { name: "Japanese Traditional", contentfulId: "6xQVmipttyvrVjpSBB9a1g" },
  { name: "Synth", contentfulId: "2RXZR6Ifat9X1xpu1oNPAZ" },
  { name: "Brazilian Experimental", contentfulId: "7taxlefUIWxsKbf1JC3gol" },
  { name: "Rave", contentfulId: "7swMb8eFAuMOiWjBj0TpdU" },
  { name: "Kosmische", contentfulId: "GxUOxF2YXQmwqhIMuAPrq" },
  { name: "Psych", contentfulId: "j0KrXQOVRKE1zEdwj1TCv" },
  { name: "Prog House", contentfulId: "4KQTQ2Lg86Cfe6ccjlu9dc" },
  { name: "Atmospheric", contentfulId: "5FPKLrCcmALpeZPR3UgFvW" },
  { name: "Soundscape", contentfulId: "5aWqnCUmDDfuEMSfHrqvOY" },
  { name: "Sound Design", contentfulId: "22Wprv19pFgQJqzASuYTVu" },
  { name: "Pop", contentfulId: "79EFvQoEI4cX4DRSm4R2VA" },
  { name: "Trap", contentfulId: "6LkRUr752kNAZn6BDFi4d4" },
  { name: "Hardcore", contentfulId: "lxX34XhXSDdel5MU167kw" },
  { name: "UK", contentfulId: "71Ye4RYETu94nf2VemZZ4O" },
  { name: "Jersey Club", contentfulId: "UUK1GXRRwv43MnNnTcq4T" },
  { name: "Electronic", contentfulId: "pWlduk8ms8rCjJg9xTy0T" },
  { name: "Easy Listening", contentfulId: "6LtJ6Yc0pYD8eqFvWR88pi" },
  { name: "New Age", contentfulId: "6u7xdROPXSeRKDc9BMUWqd" },
  { name: "Indie", contentfulId: "2h4I8fvnRPuMKYc8Koi4Li" },
  { name: "Rock & Roll", contentfulId: "4RgfFcLT1WgUw3AXkycrJx" },
  { name: "Alternative Pop", contentfulId: "1W1L2dTSrX7gKLSg8OC6k1" },
  { name: "Obscure Dance", contentfulId: "3EuU17ngSTDy2qeWs3GgYi" },
  { name: "Outsider Rock", contentfulId: "78o9TZ4LNIsYI4QQ7hVteQ" },
  { name: "Italo", contentfulId: "97kS84l8swlxVzv9jiONd" },
  { name: "Cosmic", contentfulId: "4LsT4Hk5agLFAevDo4UoSP" },
  { name: "Chopped & Screwed", contentfulId: "2ODIVaLRUJb0lfys62uoIz" },
  { name: "Chillout", contentfulId: "7zUbZvDxiCqkoplIrBz6wo" },
  { name: "Soul", contentfulId: "3lO7YrhoJGlucJ9ZfuhqOV" },
  { name: "Psychedelic Jazz", contentfulId: "6mmwLZg4bLx5nszJaClW8u" },
  { name: "Psychedelic", contentfulId: "6qYvy9IvTAUhLrIawIa1To" },
  { name: "Psychedelic Rock", contentfulId: "6kYfL5ECd8aRLy0Jq3T1Lw" },
  { name: "UK Techno", contentfulId: "1c3PYn8XECpiazNiVxN8eC" },
  { name: "Dancehall", contentfulId: "1tykESCLFoJcxDWT8O2QKz" },
  { name: "UK Bass", contentfulId: "1lCvrknV66PF500nnWQ0Ug" },
  { name: "Drum & Bass", contentfulId: "5k5mxnu2EERkk5PzesVDon" },
  { name: "Jungle", contentfulId: "4QtLDwuChgobbWM2mEtMGW" },
  { name: "Drumfunk", contentfulId: "4YJ8iHuOYmYIxU6W5PfaqP" },
  { name: "IDM", contentfulId: "OXZAKlrGT2ZNWbpsk0iSp" },
  { name: "EBM", contentfulId: "tTTX3R0oosle9EOQsjk2t" },
  { name: "Ghetto House", contentfulId: "3GBYZUJA7FiPUlFvwkOH7c" },
  { name: "Footwork", contentfulId: "2mVeEHqU8HbS7g4bqCkc1t" },
  { name: "Acid", contentfulId: "7yqgTQbh1iEDFm5k8DH06Z" },
  { name: "Lounge", contentfulId: "246crvlDu7xC9Z6sQzrLh5" },
  { name: "Experimental", contentfulId: "3035gySHG4nww16aCw2wGn" },
  { name: "Club", contentfulId: "5NxjyPNtfA3MAsJWZa06qK" },
  { name: "Breaks", contentfulId: "6UNq7Z6JuIxxktZ5uF9WZC" },
  { name: "Panel", contentfulId: "41zCHAHIhb6XjXQbZgbr5j" },
  { name: "Drill", contentfulId: "6vDvMBMH3IrES01798q9X6" },
  { name: "Tech House", contentfulId: "6Ou1f1qa7IteoE60EkepnR" },
  { name: "Deep House", contentfulId: "6teuk0BsaEpmf3ypvo8z84" },
  { name: "Soundtrack", contentfulId: "20gVTGFqeV2IS1kiQiufNB" },
  { name: "Trip Hop", contentfulId: "4AmKvXfpxL3dnYj79EtnTD" },
  { name: "Balearic", contentfulId: "7cZGwMrIghTkODH5wC3oOm" },
  { name: "Gospel", contentfulId: "7rrBrmgdpqi0xtetKXGN8O" },
  { name: "Industrial", contentfulId: "2vRUVr2XOXjAY3lOYKJoXa" },
  { name: "Hip-Hop", contentfulId: "67PiGVYS1EsuN2l7E46GJX" },
  { name: "Synth Pop", contentfulId: "Ggtz1t7kpZW6UsCI8u3Ko" },
  { name: "Post Punk", contentfulId: "1OBNFaQXSFyevrihq4KjlH" },
  { name: "Jazz", contentfulId: "3bGxNQPYgGAcd9Rz0KeXuT" },
  { name: "Folk", contentfulId: "5MbklWwoo2pzpppD94Zbay" },
  { name: "Blues", contentfulId: "7DjlqTH3hNAvR5vO3so04f" },
  { name: "Punk", contentfulId: "3bEi3m0CoEdQmWzLcSdscF" },
  { name: "New Wave", contentfulId: "1dLfITRl83SW6AbI88bXFa" },
  { name: "Rap", contentfulId: "32JXuf6klbOLjhITXi9ZQa" },
  { name: "Beats", contentfulId: "7j7MgNfnKck6WtUe7jFES3" },
  { name: "Rhythm & Blues", contentfulId: "2pQDYq6f7ctCfz1TnHoXZ" },
  { name: "UK Funky", contentfulId: "6foh6YfGqMvDwDSxMYtNI0" },
  { name: "Grime", contentfulId: "4cnfEFOVMO7EpQ5uf4z7y1" },
  { name: "Leftfield", contentfulId: "6McAPiRC9Qwj53TwBAjCx1" },
  { name: "Field Recordings", contentfulId: "yfteQngriEss6Jt56jrH7" },
  { name: "Downtempo", contentfulId: "6NSW9iCEuOiZ3sX8t8MPID" },
  { name: "Dub", contentfulId: "6hi3ogh4pzJM1e2sYEtDIN" },
  { name: "Disco", contentfulId: "7em3eAtMcbXSLUyDW5blmN" },
  { name: "Classical", contentfulId: "3hywJhFbreJEQ5nyQ2REm9" },
  { name: "Boogie", contentfulId: "756L37CnOKBoPlrU5bPRPV" },
  { name: "Alternative Rock", contentfulId: "78Bi6nG8epbHQqshKigMj4" },
  { name: "Afrobeat", contentfulId: "6eMArK1AAeZXvmnOdW10yp" },
  { name: "Avant Garde", contentfulId: "HKvYhLO9ISnEvP990iMwI" },
  { name: "Ambient", contentfulId: "39Rd7p14jTxdIhKA9tc6zm" },
  { name: "Talk Show", contentfulId: "73cNrkBvVM7OLCKprxnCOO" },
  { name: "Discussion", contentfulId: "6M9fTkzk3k8luwvaFB5Utl" },
  { name: "Spoken Word", contentfulId: "3aFdo0imShteO8c0nE5FuA" },
  { name: "Reggae", contentfulId: "5NfGDYg5FLPSRIpl8qRUuB" },
  { name: "Dub Techno", contentfulId: "6oDKVLLVwf3rqJ06Cu83J1" },
  { name: "Detroit Techno", contentfulId: "VY3GXSiz7HSVu0UTRdJm4" },
  { name: "2-Step", contentfulId: "2hmI7eCA2aq6QKwHAZIpYh" },
  { name: "Broken Beat", contentfulId: "1QZeiCZ1XwZDZ0q8BqoC2k" },
  { name: "Bass", contentfulId: "5JzWP30bYw9k0vc7YDLPdp" },
  { name: "Garage", contentfulId: "1Jf356lmc0BWJd5dEs2W50" },
  { name: "Trance", contentfulId: "1YaWgBhmD8QHa9BLu2dZDm" },
  { name: "Breakbeat", contentfulId: "5yMqeWlB1sUsp22725ZheD" },
  { name: "Electro", contentfulId: "4mG6xpT0yxpVME4ANipfa7" },
  { name: "House", contentfulId: "28hEbrh54tJ1qFxZIMVf3g" },
  { name: "Techno", contentfulId: "7KJR6pIrqraqpXBsRApN3R" },
];
